"""Added required tables

Revision ID: 44fc87e16786
Revises: 70193fcb4dde
Create Date: 2022-06-20 09:40:40.919077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44fc87e16786"
down_revision = "70193fcb4dde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mas_predicted",
        sa.Column("mas_length_up", sa.Integer(), nullable=True),
    )
    op.add_column(
        "mas_predicted",
        sa.Column("mas_length_down", sa.Integer(), nullable=True),
    )
    op.add_column(
        "mas_predicted",
        sa.Column("mas_length_middle", sa.Integer(), nullable=True),
    )
    op.add_column(
        "mas_predicted",
        sa.Column("mas_length_middle_up", sa.Integer(), nullable=True),
    )
    op.add_column(
        "mas_predicted",
        sa.Column("mas_length_middle_down", sa.Integer(), nullable=True),
    )
    op.add_column(
        "mas_predicted",
        sa.Column("mas_heigth_middle_down", sa.Integer(), nullable=True),
    )
    op.drop_column("mas_predicted", "mas_width_middle_down")
    op.drop_column("mas_predicted", "mas_width_up")
    op.drop_column("mas_predicted", "mas_width_middle_up")
    op.drop_column("mas_predicted", "mas_height_middle_down")
    op.drop_column("mas_predicted", "mas_width_down")
    op.drop_column("mas_predicted", "mas_width_middle")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mas_predicted",
        sa.Column(
            "mas_width_middle",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mas_predicted",
        sa.Column(
            "mas_width_down", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "mas_predicted",
        sa.Column(
            "mas_height_middle_down",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mas_predicted",
        sa.Column(
            "mas_width_middle_up",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "mas_predicted",
        sa.Column(
            "mas_width_up", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "mas_predicted",
        sa.Column(
            "mas_width_middle_down",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("mas_predicted", "mas_heigth_middle_down")
    op.drop_column("mas_predicted", "mas_length_middle_down")
    op.drop_column("mas_predicted", "mas_length_middle_up")
    op.drop_column("mas_predicted", "mas_length_middle")
    op.drop_column("mas_predicted", "mas_length_down")
    op.drop_column("mas_predicted", "mas_length_up")
    # ### end Alembic commands ###
