"""Added required tables

Revision ID: b59478c5bc08
Revises: 44fc87e16786
Create Date: 2022-06-20 09:52:08.493711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b59478c5bc08"
down_revision = "44fc87e16786"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mas_predicted",
        sa.Column("mas_height_middle_down", sa.Integer(), nullable=True),
    )
    op.drop_column("mas_predicted", "mas_heigth_middle_down")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mas_predicted",
        sa.Column(
            "mas_heigth_middle_down",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("mas_predicted", "mas_height_middle_down")
    # ### end Alembic commands ###
